services:
  producer:
    build:
      context: .
      dockerfile: producer/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NUM_MAX_TASKS=${NUM_MAX_TASKS}
      - PRODUCER_PORT=${PRODUCER_PORT}
      - DEFAULT_REGION_AWS=${DEFAULT_REGION_AWS}
      - SQS_ENDPOINT_URL=http://emulator-aws:4566
      - SQS_QUEUE_URL=http://emulator-aws:4566/000000000000/scraping-tasks
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - "./producer:/app"
      - "./shared:/app/shared"
    depends_on:
      - emulator-aws

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      - NUM_MAX_TASKS=10
      - WORKER_NUM_MAX_CONCURRENT_TASKS=${WORKER_NUM_MAX_CONCURRENT_TASKS}
      - DEFAULT_REGION_AWS=${DEFAULT_REGION_AWS}
      - SQS_ENDPOINT_URL=http://emulator-aws:4566
      - SQS_QUEUE_URL=http://emulator-aws:4566/000000000000/scraping-tasks
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - PROXY_ENABLED=${PROXY_ENABLED}
      - PROXY_MODE=${PROXY_MODE}
      - PROXY_STATIC_LIST=${PROXY_STATIC_LIST}
      - PROXY_URL=${PROXY_URL}
    volumes:
      - "./worker:/app"
      - "./shared:/app/shared"
    depends_on:
      - emulator-aws
      - producer

  emulator-aws:
    image: floci/floci:latest-compat
    ports:
      - "4566:4566"
    environment:
      - DEFAULT_REGION=${DEFAULT_REGION_AWS}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - FLOCI_STORAGE_MODE=hybrid
    volumes:
      - "./infra/init-aws.sh:/etc/localstack/init/ready.d/init-aws.sh"
      - localstack_data:/app/data

volumes:
  localstack_data:
