sonar.projectKey=ArturoCarrilloJimenez_WebScrapingDistributed
sonar.organization=arturocarrillojimenez
sonar.projectName=WebScrapingDistributed
sonar.projectVersion=1.0

sonar.sources=producer,worker,shared
sonar.tests=producer/test #,worker/test

# Analizamos todo el repositorio
sonar.language=py
sonar.sources=.
sonar.python.version=3.13

# Excluir de análisis estático
sonar.exclusions=**/test/**,**/.venv/**,**/__pycache__/**,**/*.md,**/.github/**,**/uv.lock

# Configuración de cobertura y pruebas
sonar.python.coverage.reportPaths=producer/coverage.xml #,worker/coverage.xml
sonar.python.xunit.reportPath=producer/test-results.xml #,worker/test-results.xml

# Encoding
sonar.sourceEncoding=UTF-8

sonar.qualitygate.wait=true
