sonar.projectKey=WebScrapingDistributed
sonar.organization=arturo-carrillo-jimenez

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=WebScrapingDistributed
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# Analizamos todo el repositorio
sonar.sources=.

# Excluir de análisis estático
sonar.exclusions=**/test/**,**/.venv/**,**/__pycache__/**,**/*.md,**/.github/**,**/uv.lock

# Reportes de cobertura (generado por pytest en producer/)
sonar.python.coverage.reportPaths=producer/coverage.xml

# Reportes de tests
sonar.python.xunit.reportPath=producer/test-results.xml

# Encoding
sonar.sourceEncoding=UTF-8
