# 1. Deployment para la API Producer (FastAPI Ingestion API)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  namespace: web-scraping-distributed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      automountServiceAccountToken: false
      containers:
        - name: producer
          image: arturocarrillojimenez/web-scraping-producer:latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "50Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
              ephemeral-storage: "200Mi"
          envFrom:
            - configMapRef:
                name: scraping-config
          env:
            - name: SQS_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: SQS_ENDPOINT_URL
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: SQS_QUEUE_URL_STATIC
            - name: SQS_QUEUE_URL_DYNAMIC
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: SQS_QUEUE_URL_DYNAMIC
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: DEFAULT_REGION_AWS
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: DEFAULT_REGION_AWS
          # Health Checks
          readinessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /docs
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15

---

# 2. Service para exponer la API Producer a través de un puerto de nodo (NodePort)
apiVersion: v1
kind: Service
metadata:
  name: producer-service
  namespace: web-scraping-distributed
spec:
  type: NodePort
  selector:
    app: producer
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
