# Deployment para los Workers Estáticos (HTML + CSS / BeautifulSoup)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-static
  namespace: web-scraping-distributed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-static
  template:
    metadata:
      labels:
        app: worker-static
    spec:
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 60
      containers:
        - name: worker-static
          image: arturocarrillojimenez/web-scraping-worker:latest
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
              ephemeral-storage: "50Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"
              ephemeral-storage: "200Mi"
          envFrom:
            - configMapRef:
                name: scraping-config
          env:
            - name: WORKER_NUM_MAX_CONCURRENT_TASKS
              valueFrom:
                configMapKeyRef:
                  name: scraping-config
                  key: WORKER_NUM_MAX_CONCURRENT_TASKS_STATIC
            - name: PARSER_TYPE
              value: "static_css"
            - name: SQS_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: SQS_ENDPOINT_URL
            - name: SQS_QUEUE_URL
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: SQS_QUEUE_URL_STATIC
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: S3_ENDPOINT_URL
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: S3_ENDPOINT_URL
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: S3_BUCKET_NAME
            - name: DEFAULT_REGION_AWS
              valueFrom:
                secretKeyRef:
                  name: scraping-secrets
                  key: DEFAULT_REGION_AWS
