name: PR Validation & SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]

jobs:
  test-and-analyze:
    name: Test and SonarCloud Analysis
    runs-on: ubuntu-latest
    
    env:
      DEFAULT_REGION_AWS: us-east-1
      AWS_ACCESS_KEY_ID: testing 
      AWS_SECRET_ACCESS_KEY: testing
      SQS_ENDPOINT_URL: "http://localhost:4566"
      SQS_QUEUE_URL: "http://localhost:4566/000000000000/test-queue"
      NUM_MAX_TASKS: 10
      PRODUCER_PORT: 8000
      PRODUCER_HOST: "localhost"
      DEBUG_MODE: "True"


    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 0

      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"

      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405
        with:
          python-version-file: ".python-version"

      - name: Install dependencies and run tests for Producer
        working-directory: ./producer
        run: |
          uv sync --dev
          uv run pytest test/ --cov=./ --cov-report=xml --junitxml=test-results.xml

      - name: Normalize coverage and test reports
        run: |
          sed -i 's|/home/runner/work/WebScrapingDistributed/WebScrapingDistributed/||g' producer/coverage.xml
          sed -i 's|/home/runner/work/WebScrapingDistributed/WebScrapingDistributed/||g' producer/test-results.xml
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          